name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "*/6 * * * *" # Dijalankan setiap 6 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Productive Time Card
        uses: vn7n2/github-profile-summary-cards@release
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 7
          CARD_TYPE: productive-time
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push generated card
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add profile-summary-card-output/productive-time.svg
          git commit -m "Update productive-time card" || echo "No changes to commit"
          git push || echo "No changes to push"
